# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ktea < Formula
  desc "Kafka Terminal UI"
  homepage "https://github.com/jonas-grgt/ktea"
  version "0.6.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jonas-grgt/ktea/releases/download/v0.6.3/ktea_0.6.3_darwin_amd64.tar.gz"
      sha256 "ef9b9d186c2daeeafd2758489b9cee40aa57c9bc0d17dfe943eb3a2ceb68accc"

      def install
        bin.install "ktea"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jonas-grgt/ktea/releases/download/v0.6.3/ktea_0.6.3_darwin_arm64.tar.gz"
      sha256 "356dc0ceb9a58a9b11678ab5ecec724c1fbe4df78e90c604ee20e44d1f8cd9fa"

      def install
        bin.install "ktea"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jonas-grgt/ktea/releases/download/v0.6.3/ktea_0.6.3_linux_amd64.tar.gz"
      sha256 "2b93d5d3075662f08b2eca72222c770580ab3929f302978a0371d055b2272a79"
      def install
        bin.install "ktea"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/jonas-grgt/ktea/releases/download/v0.6.3/ktea_0.6.3_linux_arm.tar.gz"
      sha256 "847f53faebbc1e28134f1e7b807e31bae61252a13f7a41bfda5112f14aa93194"
      def install
        bin.install "ktea"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jonas-grgt/ktea/releases/download/v0.6.3/ktea_0.6.3_linux_arm64.tar.gz"
      sha256 "e49ae739e491692186743810f4e0e9b5fd362eb75494b00d503c2b9c2ea671f4"
      def install
        bin.install "ktea"
      end
    end
  end
end
