# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ktea < Formula
  desc "Kafka Terminal UI"
  homepage "https://github.com/jonas-grgt/ktea"
  version "0.6.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jonas-grgt/ktea/releases/download/v0.6.2/ktea_0.6.2_darwin_amd64.tar.gz"
      sha256 "7f5f2bbf462bb666a9374711e4f2df341b0bad8ffd0d381a99d4154dd7ee6279"

      def install
        bin.install "ktea"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jonas-grgt/ktea/releases/download/v0.6.2/ktea_0.6.2_darwin_arm64.tar.gz"
      sha256 "260a6e71e355e7bd9d38de8fb33bf2334f8b4486f7728a55d21795764c982b26"

      def install
        bin.install "ktea"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jonas-grgt/ktea/releases/download/v0.6.2/ktea_0.6.2_linux_amd64.tar.gz"
      sha256 "b7338d0387e677ee0a12d89a1f5ca258b5f1c96eb810e6f5fd9272e3569cb38e"
      def install
        bin.install "ktea"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/jonas-grgt/ktea/releases/download/v0.6.2/ktea_0.6.2_linux_arm.tar.gz"
      sha256 "827af18375bf7c1541c7fc6d51faa88fa913b62505736b13abc58bded1aff9d0"
      def install
        bin.install "ktea"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jonas-grgt/ktea/releases/download/v0.6.2/ktea_0.6.2_linux_arm64.tar.gz"
      sha256 "0fcfcb0e3f5270f10a40f348c1566fc0dd7273c00b488879a5e31b587ec9ca59"
      def install
        bin.install "ktea"
      end
    end
  end
end
